export const SET_CHALLENGE = "SET_CHALLENGE";
export const REMOVE_CHALLENGE = "REMOVE_CHALLENGE";
export const START_THE_GAME = "START_THE_GAME";
export const END_THE_GAME = "END_THE_GAME";
export const DO_CHALLENGE = "DO_CHALLENGE";
